// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/api/cal-webhook": {
    params: {};
  };
  "/canvas-preview": {
    params: {};
  };
  "/capabilities": {
    params: {};
  };
  "/case-studies": {
    params: {};
  };
  "/case-studies/:slug": {
    params: {
      "slug": string;
    };
  };
  "/company": {
    params: {};
  };
  "/content": {
    params: {};
  };
  "/content/articles": {
    params: {};
  };
  "/content/articles/:slug": {
    params: {
      "slug": string;
    };
  };
  "/content/podcast": {
    params: {};
  };
  "/content/podcast/:slug": {
    params: {
      "slug": string;
    };
  };
  "/content/events": {
    params: {};
  };
  "/content/net-zero": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/always-on": {
    params: {};
  };
  "/guest-on-our-podcast": {
    params: {};
  };
  "/privacy": {
    params: {};
  };
  "/terms": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/api/cal-webhook" | "/canvas-preview" | "/capabilities" | "/case-studies" | "/case-studies/:slug" | "/company" | "/content" | "/content/articles" | "/content/articles/:slug" | "/content/podcast" | "/content/podcast/:slug" | "/content/events" | "/content/net-zero" | "/contact" | "/always-on" | "/guest-on-our-podcast" | "/privacy" | "/terms" | "/*";
  };
  "./pages/api.cal-webhook.js": {
    id: "pages/api.cal-webhook";
    page: "/api/cal-webhook";
  };
  "./pages/CanvasPreview.jsx": {
    id: "pages/CanvasPreview";
    page: "/canvas-preview";
  };
  "./components/Layout.jsx": {
    id: "components/Layout";
    page: "/" | "/capabilities" | "/case-studies" | "/case-studies/:slug" | "/company" | "/content" | "/content/articles" | "/content/articles/:slug" | "/content/podcast" | "/content/podcast/:slug" | "/content/events" | "/content/net-zero" | "/contact" | "/always-on" | "/guest-on-our-podcast" | "/privacy" | "/terms" | "/*";
  };
  "./pages/HomePage.jsx": {
    id: "pages/HomePage";
    page: "/";
  };
  "./pages/CapabilitiesPage.jsx": {
    id: "pages/CapabilitiesPage";
    page: "/capabilities";
  };
  "./pages/CaseStudiesIndex.jsx": {
    id: "pages/CaseStudiesIndex";
    page: "/case-studies";
  };
  "./pages/CaseStudyDetail.jsx": {
    id: "pages/CaseStudyDetail";
    page: "/case-studies/:slug";
  };
  "./pages/CompanyPage.jsx": {
    id: "pages/CompanyPage";
    page: "/company";
  };
  "./pages/ContentPage.jsx": {
    id: "pages/ContentPage";
    page: "/content";
  };
  "./pages/ArticlesPage.jsx": {
    id: "pages/ArticlesPage";
    page: "/content/articles";
  };
  "./pages/ArticleDetail.jsx": {
    id: "pages/ArticleDetail";
    page: "/content/articles/:slug";
  };
  "./pages/PodcastPage.jsx": {
    id: "pages/PodcastPage";
    page: "/content/podcast";
  };
  "./pages/PodcastCampaignOrDetail.jsx": {
    id: "pages/PodcastCampaignOrDetail";
    page: "/content/podcast/:slug";
  };
  "./pages/EventsPage.jsx": {
    id: "pages/EventsPage";
    page: "/content/events";
  };
  "./pages/NetZeroPage.jsx": {
    id: "pages/NetZeroPage";
    page: "/content/net-zero";
  };
  "./pages/ContactPage.jsx": {
    id: "pages/ContactPage";
    page: "/contact";
  };
  "./pages/AlwaysOnPage.jsx": {
    id: "pages/AlwaysOnPage";
    page: "/always-on";
  };
  "./pages/GuestPage.jsx": {
    id: "pages/GuestPage";
    page: "/guest-on-our-podcast";
  };
  "./pages/PrivacyPage.jsx": {
    id: "pages/PrivacyPage";
    page: "/privacy";
  };
  "./pages/TermsPage.jsx": {
    id: "pages/TermsPage";
    page: "/terms";
  };
  "./pages/NotFoundPage.jsx": {
    id: "pages/NotFoundPage";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./src/root.jsx");
  "pages/api.cal-webhook": typeof import("./src/./pages/api.cal-webhook.js");
  "pages/CanvasPreview": typeof import("./src/./pages/CanvasPreview.jsx");
  "components/Layout": typeof import("./src/./components/Layout.jsx");
  "pages/HomePage": typeof import("./src/./pages/HomePage.jsx");
  "pages/CapabilitiesPage": typeof import("./src/./pages/CapabilitiesPage.jsx");
  "pages/CaseStudiesIndex": typeof import("./src/./pages/CaseStudiesIndex.jsx");
  "pages/CaseStudyDetail": typeof import("./src/./pages/CaseStudyDetail.jsx");
  "pages/CompanyPage": typeof import("./src/./pages/CompanyPage.jsx");
  "pages/ContentPage": typeof import("./src/./pages/ContentPage.jsx");
  "pages/ArticlesPage": typeof import("./src/./pages/ArticlesPage.jsx");
  "pages/ArticleDetail": typeof import("./src/./pages/ArticleDetail.jsx");
  "pages/PodcastPage": typeof import("./src/./pages/PodcastPage.jsx");
  "pages/PodcastCampaignOrDetail": typeof import("./src/./pages/PodcastCampaignOrDetail.jsx");
  "pages/EventsPage": typeof import("./src/./pages/EventsPage.jsx");
  "pages/NetZeroPage": typeof import("./src/./pages/NetZeroPage.jsx");
  "pages/ContactPage": typeof import("./src/./pages/ContactPage.jsx");
  "pages/AlwaysOnPage": typeof import("./src/./pages/AlwaysOnPage.jsx");
  "pages/GuestPage": typeof import("./src/./pages/GuestPage.jsx");
  "pages/PrivacyPage": typeof import("./src/./pages/PrivacyPage.jsx");
  "pages/TermsPage": typeof import("./src/./pages/TermsPage.jsx");
  "pages/NotFoundPage": typeof import("./src/./pages/NotFoundPage.jsx");
};