export const articles = [
  {
    slug: "from-legacy-to-governed-in-a-week",
    title: "From Legacy to Governed in a Week",
    author: "Julian Tedstone",
    date: "2026-03-16",
    image: "article-rebuilt-in-days.jpg",
    intro:
      "Most agencies sell a six-month discovery phase before a single line of production code ships. Always On clients go from legacy codebase to a governed, continuously improving front end in their first sprint. Here is exactly how that works.",
    sections: [
      {
        heading: "Day One: Extracting What Already Works",
        body: "The first thing we do when a new Always On engagement starts is pull your existing site apart in a structured way. Not to throw it away, but to understand it. Our tooling crawls every page, captures the visual language, catalogues the components, and maps the content. Within hours we have a complete picture of your current state: the typography scale, the colour tokens, the spacing rhythm, the component inventory. This is not a redesign exercise. We are not asking you to imagine a future state or sit through workshops about brand values. We are reading the site you already have and turning implicit decisions into explicit, versioned tokens. The output of day one is a design system snapshot. It tells us what is consistent, what has drifted, and where the gaps are. Clients are often surprised by how much of their visual identity is already coherent. The problem is rarely that the design is broken. The problem is that nobody has written the rules down, so every new page is a fresh interpretation. By the end of the first day, the rules exist. They are machine-readable, version-controlled, and ready to enforce.",
      },
      {
        heading: "Days Two and Three: Standing Up the Governed Front End",
        body: "With the design system extracted, we generate a governed front end. This is a production-grade build that uses your tokens, your components, and your content, but wraps them in a structure that can be continuously improved without regression. The key word is governed. Every component renders from the token set. Every layout decision traces back to a documented rule. When something changes, we know what changed, why, and what it affected. This is where Always On diverges from the traditional agency model. A conventional rebuild gives you a pristine site on launch day and watches it decay from there. Our governed front end is designed to get better over time because the system knows what good looks like and can measure drift against it. During these two days, we also connect the five operational pipelines: CodeOps for deployment and build integrity, SecurityOps for dependency and vulnerability monitoring, ContentOps for structured content management, DecisionOps for logging every change with rationale, and ContextOps for cross-pipeline coordination. The site is not just live. It is observable, auditable, and ready for iteration.",
      },
      {
        heading: "Days Four and Five: Handover to the Continuous Cycle",
        body: "The final two days of the first sprint are about transition. We walk clients through their governance dashboard, show them where to find the backlog, and explain the monthly cadence that starts immediately. There is no gap between project delivery and ongoing service. The engagement is continuous from the first commit. We run through the first set of improvement candidates. These are opportunities our pipelines identified during extraction: accessibility gaps, performance bottlenecks, SEO issues, content inconsistencies. Each one is logged, prioritised, and ready to enter the first monthly improvement cycle. Clients also meet their dedicated team. Always On is not a faceless retainer. There is a named operator for each pipeline, a monthly review call, and a shared backlog that clients can see and contribute to at any time. By Friday, the client has a governed front end in production, a populated improvement backlog, five operational pipelines running, and a clear picture of what happens next. The old site is not gone. It has been understood, formalised, and placed on a trajectory of measured improvement. That is what we mean by governed.",
      },
      {
        heading: "Why Speed Matters Here",
        body: "A week is not a gimmick. It is a design constraint that forces us to do the right things in the right order. Long discovery phases exist because agencies need time to understand a codebase they did not build. Our tooling removes that bottleneck. Automated extraction means we understand your site in hours, not months. The speed also serves a practical purpose for clients. Every week your legacy site runs unmonitored is a week where security vulnerabilities go unpatched, performance degrades without measurement, and content drifts further from your brand standards. The first sprint closes that exposure window. Once the governed front end is live, every subsequent improvement is incremental, measured, and reversible. There is no big bang relaunch, no holding-your-breath go-live weekend. The site improves continuously, and you can see the evidence in your dashboard every day. Clients who have been through the process consistently say the same thing: they expected to feel rushed, but instead they felt clarity. When the system does the heavy lifting of extraction and governance setup, the humans can focus on priorities and direction. That is the point. Technology handles the structure. People handle the strategy.",
      },
    ],
  },
  {
    slug: "what-always-on-actually-means-in-practice",
    title: "What Always On Actually Means in Practice",
    author: "Julian Tedstone",
    date: "2026-03-16",
    image: "article-end-of-redesign.jpg",
    intro:
      "The annual redesign cycle is broken. You spend six months and a significant budget building a new site, launch it, and immediately start the slow slide back toward something that needs replacing again. Always On is the alternative: continuous improvement delivered as a managed service.",
    sections: [
      {
        heading: "The Problem with Projects",
        body: "Traditional web projects follow a predictable arc. There is a burst of activity, a launch, and then a long decline. The site looks perfect on day one. By month three, someone has added an off-brand banner. By month six, a dependency has fallen behind and nobody has updated it. By month twelve, the team is talking about a redesign. This cycle wastes money, but more importantly it wastes the institutional knowledge that went into the original build. Every redesign starts from scratch because nobody documented the decisions that shaped the last one. The content strategy, the component rationale, the accessibility fixes: all of it gets thrown away and rebuilt from memory. Always On breaks this cycle by treating your website as a living product rather than a project with an end date. There is no launch day because the site is always launching. There is no decay period because every month includes scheduled improvements. And there is no knowledge loss because every decision is logged and searchable. The shift is not just operational. It changes the relationship between a business and its web presence from periodic anxiety to steady confidence.",
      },
      {
        heading: "The Monthly Cadence",
        body: "Every Always On engagement follows a monthly rhythm. At the start of each month, we review the improvement backlog with the client. This backlog is populated from three sources: pipeline-detected opportunities such as performance regressions or accessibility issues, client requests and business priorities, and strategic recommendations from the team. Together we select the items for that month's cycle. There is a fixed capacity, which keeps scope predictable and budgets stable. The selected items are implemented, tested, and deployed within the month. Every change goes through the governance layer, which means it is checked against the design system, validated for accessibility, and logged with a rationale. At the end of the month, clients receive a report showing what changed, what improved, and what the pipelines are recommending for next month. This cadence does three things. It keeps the site improving continuously. It gives clients a predictable cost and a clear view of what they are getting. And it creates a compounding record of decisions that makes the site smarter and more consistent over time. No surprises, no scope creep, no ambiguity about what was delivered.",
      },
      {
        heading: "What Clients See in the First 90 Days",
        body: "The first month is the onboarding sprint. The design system is extracted, the governed front end is deployed, and the five pipelines are connected. Clients finish month one with a production site that is actively monitored and a backlog of improvement candidates. Month two is the first full improvement cycle. Clients experience the cadence for the first time: backlog review, implementation, deployment, reporting. This is where the model starts to feel different from anything they have experienced with a traditional agency. There are no change requests lost in email threads. There are no surprise invoices. Everything is visible in the shared backlog and dashboard. By month three, the compounding effect is visible. The site has had two full cycles of measured improvement. Performance metrics show trends. Accessibility scores are tracked over time. Content consistency has improved because the governance layer catches drift before it reaches production. Clients also start to notice something subtler. They stop worrying about their website. The anxiety that comes with knowing your site is slowly degrading is replaced by confidence that it is actively getting better. That shift in mindset is the real product we deliver. The technical output is the mechanism, but the outcome is peace of mind.",
      },
      {
        heading: "Why This Model Wins",
        body: "The economics are straightforward. A typical redesign costs a significant lump sum every two to three years. Always On costs a predictable monthly amount and delivers continuous value. Over a three-year period, clients spend less and get more. But the financial argument is not the strongest one. The strongest argument is quality. A redesign gives you a single moment of peak quality followed by decline. Always On gives you a steady upward trajectory. Every month, the site is better than the month before. Every decision is documented. Every change is reversible. The model also scales naturally. As business needs change, the backlog adapts. A product launch, a regulatory change, a rebrand: these become items in the improvement cycle rather than triggers for a new project. The infrastructure is already in place to handle them. We built Always On because we saw the same pattern too many times. Good agencies delivering good work that decayed because there was no structure to maintain and improve it after launch. The technology to solve this problem exists now. Automated extraction, governed design systems, observable pipelines, continuous deployment. The question is not whether continuous improvement is possible. It is whether you are ready to stop paying for entropy and start paying for progress.",
      },
    ],
  },
  {
    slug: "how-we-run-five-pipelines-without-things-falling-through-the-cracks",
    title:
      "How We Run Five Pipelines Without Things Falling Through the Cracks",
    author: "Julian Tedstone",
    date: "2026-03-16",
    image: "article-agents-talk.jpg",
    intro:
      "Always On runs five operational pipelines across every client engagement: CodeOps, SecurityOps, ContentOps, DecisionOps, and ContextOps. That is a lot of moving parts. Here is how we keep everything coordinated, transparent, and accountable.",
    sections: [
      {
        heading: "The Coordination Problem",
        body: "Running multiple operational pipelines simultaneously creates an obvious risk: duplication, contradiction, and gaps. If CodeOps deploys a change that SecurityOps has not reviewed, you have a problem. If ContentOps updates a page that DecisionOps has not logged, you lose traceability. If two pipelines independently identify the same issue and both try to fix it, you get conflicts. In a traditional agency, coordination happens through people. Project managers hold the context, relay information between teams, and try to keep everything aligned through meetings and status updates. This works until it does not. People forget things, misunderstand priorities, and go on holiday. The coordination layer needs to be systematic, not heroic. That is what ContextOps provides. It is the fifth pipeline, and its entire purpose is to ensure the other four are aware of each other. Every action taken by any pipeline is registered in a shared context layer. Before any pipeline acts, it checks what the others have done and what they are planning. This is not a status dashboard. It is an active coordination mechanism that prevents conflicts before they happen and ensures nothing is missed.",
      },
      {
        heading: "How ContextOps Works in Practice",
        body: "Every pipeline action follows a consistent pattern: propose, check, execute, log. When CodeOps identifies a dependency update, it proposes the change. ContextOps checks whether SecurityOps has any holds on that dependency, whether ContentOps has any pages that depend on the affected component, and whether DecisionOps has any relevant prior decisions. Only when the context is clear does the change proceed. After execution, the action is logged with its rationale, its scope, and its outcome. This log is not just an audit trail. It is a knowledge base that makes future decisions faster and more consistent. When a similar situation arises three months later, the team can see exactly what was done before and why. For clients, the practical effect is transparency. Every action taken on their site is visible, explained, and traceable. There are no black boxes. If a client asks why a particular change was made, we can show them the proposal, the context check, and the decision log. This level of accountability is unusual in the agency world, but it is standard in Always On because the system requires it. Transparency is not a policy. It is an architectural feature.",
      },
      {
        heading: "What Clients Actually See",
        body: "Clients interact with the coordination layer through their governance dashboard. This is a single view that shows the current state of all five pipelines: what has been completed, what is in progress, and what is planned. Each item links to its decision log, so clients can drill into the detail if they want to or stay at the summary level if they prefer. The dashboard also surfaces pipeline recommendations. These are actions that the system has identified as beneficial but that require client input before proceeding. For example, SecurityOps might flag a dependency that needs updating but that could affect a specific user-facing feature. The recommendation appears in the dashboard with context: what the risk is, what the proposed fix involves, and what the impact might be. Clients approve, defer, or ask questions. This is a fundamentally different relationship from the traditional agency model, where clients either micromanage every change or hand over control entirely and hope for the best. Always On gives clients the right level of involvement. Strategic decisions stay with the client. Operational execution stays with the team. And the coordination layer ensures nothing falls between the two. The result is that clients feel informed without feeling overwhelmed, and the team operates efficiently without feeling unsupervised.",
      },
      {
        heading: "Why This Matters for Ongoing Engagements",
        body: "The value of systematic coordination compounds over time. In the first month, the context layer is mostly capturing baseline decisions and establishing patterns. By month six, it has a rich history of what has been done, what worked, and what was deferred and why. This history makes the team faster and more accurate. New team members can onboard by reading the decision log. Recurring issues are handled consistently because the precedent is documented. And when clients ask for a change that was previously considered and rejected, we can show them the original reasoning and discuss whether circumstances have changed. This is the operational maturity that most agencies never achieve because they rely on institutional memory rather than institutional systems. People leave, context is lost, and mistakes are repeated. Always On builds the institutional memory into the infrastructure itself. For clients, this means their engagement gets better over time, not just because the site improves, but because the team operating it becomes more knowledgeable and more efficient with every cycle. The coordination layer is not overhead. It is the mechanism that turns a collection of services into a coherent, continuously improving operation. Without it, five pipelines would be five sources of noise. With it, they are one system working toward the same goals.",
      },
    ],
  },
  {
    slug: "the-first-thing-we-do-with-a-new-always-on-client",
    title: "The First Thing We Do with a New Always On Client",
    author: "Julian Tedstone",
    date: "2026-03-16",
    image: "article-one-design-system.jpg",
    intro:
      "Before we write a line of code, before we discuss strategy, before we plan improvements, we do one thing: extract the design system from the client's existing site. It is the foundation of everything that follows, and it is why Always On engagements start strong and stay consistent.",
    sections: [
      {
        heading: "Why the Design System Comes First",
        body: "Every website has a design system. Most of them are just not written down. The colours are chosen but not documented. The spacing is consistent on some pages and improvised on others. The typography follows a pattern that the original designer understood intuitively but never codified. This implicit design system is the reason sites drift. When there are no explicit rules, every new page is an interpretation. Each developer makes reasonable choices that are slightly different from the last developer's reasonable choices. Over months and years, these small differences accumulate into visual inconsistency that erodes brand trust. Extracting the design system makes the implicit explicit. Our tooling analyses every page of the existing site and identifies the actual patterns in use: the real colour palette, the actual type scale, the spacing values that appear most frequently, the component structures that repeat across pages. The output is not aspirational. It is descriptive. It tells us what the site actually does, not what someone hoped it would do. This distinction matters because it means we are working with reality from day one. We are not imposing an idealised system that conflicts with existing content. We are formalising the system that already exists and then improving it incrementally.",
      },
      {
        heading: "What the Extraction Process Looks Like",
        body: "The extraction is automated but not unsupervised. Our tooling crawls the site, captures rendered output at multiple viewport widths, and runs analysis passes to identify tokens and components. Tokens are the atomic values: colours, font sizes, spacing units, border radii, shadows. Components are the recurring structures: navigation patterns, card layouts, form elements, footer configurations. The automated pass produces a draft system. A human designer then reviews it, resolving ambiguities and making judgement calls. When the crawler finds four slightly different shades of blue, someone needs to decide whether those are intentional variants or drift. When spacing values cluster around 16px and 18px, someone decides whether to normalise to one value or preserve both with distinct semantic purposes. This review step is critical. Pure automation would produce a system that is technically accurate but semantically meaningless. The human layer adds intent. The result is a token set and component inventory that is both machine-readable and human-understandable. It captures what the site does and documents why those choices exist. This becomes the single source of truth for every subsequent decision in the engagement.",
      },
      {
        heading: "What the Design System Unlocks",
        body: "With the design system extracted and formalised, three things become possible. First, governance. Every new component and every content update can be validated against the token set. If someone tries to introduce an off-brand colour or a non-standard spacing value, the system catches it before it reaches production. Drift stops being an inevitable side effect of ongoing work and becomes an active choice that requires justification. Second, measurable consistency. We can score every page against the design system and track that score over time. Clients see a concrete metric that represents brand consistency, and they watch it improve month over month. This transforms design quality from a subjective opinion into an objective measurement. Third, efficient iteration. When the design system is codified, changes propagate systematically. Updating a colour token updates every component that uses it. Adjusting the type scale adjusts every page that references it. This means improvements are faster to implement, cheaper to test, and impossible to apply inconsistently. The design system is not a deliverable that sits in a documentation site and gets ignored. It is the active operating layer of the governed front end. Every component renders from it. Every change is validated against it. It is the reason Always On sites get more consistent over time instead of less.",
      },
      {
        heading: "Setting the Foundation for Everything Else",
        body: "The design system extraction takes place in the first days of an Always On engagement, and everything else builds on top of it. The governed front end uses the tokens as its rendering foundation. ContentOps validates new content against the component inventory. CodeOps checks that every build conforms to the system. DecisionOps logs any changes to the token set with rationale. Without the design system, these pipelines would have no reference point. They would be monitoring activity without any definition of correctness. The design system provides that definition. It answers the question every pipeline needs answered: what should this site look like, and how should it behave? This is also why we resist the temptation to redesign during extraction. The goal of the first sprint is not to make the site perfect. It is to make the site understood. Once it is understood, improvements are targeted, measurable, and reversible. Clients who have been through the process often tell us it was the first time they truly understood their own site. Not the brand guidelines document that nobody reads, but the actual, living system of decisions that shapes what their customers see. That understanding is the foundation of a productive ongoing relationship. It turns conversations about web changes from subjective debates into evidence-based decisions. And that is exactly the kind of relationship Always On is designed to sustain.",
      },
    ],
  },
  {
    slug: "what-always-on-clients-pay-for",
    title: "What Always On Clients Pay For",
    author: "Julian Tedstone",
    date: "2026-03-16",
    image: "article-run-improve-govern.jpg",
    intro:
      "Always On is built on three pillars: Run, Improve, and Govern. Together they form a managed website operations service that replaces the traditional agency project model with something predictable, transparent, and continuously valuable. Here is what each pillar includes and what clients actually receive.",
    sections: [
      {
        heading: "Run: Keeping the Lights On, Properly",
        body: "Run covers everything required to keep a website operational, secure, and performant. This is not passive hosting. It is active operations. The Run pillar includes uptime monitoring with defined response times, security patching and dependency updates managed through SecurityOps, performance monitoring with automated alerts when metrics degrade, SSL certificate management and renewal, backup verification and disaster recovery testing, and CDN configuration and optimisation. Every Run activity is logged and reported. Clients see exactly what was done, when, and why. There are no mystery invoices for emergency fixes because the fixes happen before they become emergencies. The Run pillar exists because most agencies treat operational maintenance as an afterthought. They build the site and hand over the keys, leaving the client to manage hosting, security, and performance on their own or through an underfunded support contract. Always On treats operations as a first-class concern. The site is not just built. It is actively maintained by people who understand it deeply because they also handle the Improve and Govern pillars. This integration matters. The team running your site is the same team improving it, which means operational knowledge feeds directly into improvement decisions.",
      },
      {
        heading: "Improve: Getting Better Every Month",
        body: "The Improve pillar is where Always On delivers its most visible value. Each month, a defined capacity of improvement work is allocated to the client's site. This work is selected from a prioritised backlog that combines three input sources: automated pipeline recommendations covering performance, accessibility, SEO, and content quality, client-initiated requests and business priorities, and strategic recommendations from the Always On team based on industry trends and best practice evolution. The monthly improvement cycle follows a consistent pattern. At the start of the month, the backlog is reviewed and items are selected. Mid-month, the selected items are implemented and tested. At the end of the month, changes are deployed and a report is delivered showing what changed and what impact it had. This cadence is predictable by design. Clients know exactly how much improvement capacity they have each month and can plan accordingly. There are no surprise costs, no scope negotiations, and no ambiguity about what was delivered. Over time, the improvements compound. A site that receives twelve months of structured, measured improvement is fundamentally better than it was at the start, and the evidence is documented in the reporting history. This is the core value proposition: not a single moment of quality, but a sustained trajectory of measurable progress.",
      },
      {
        heading: "Govern: The Rules That Make It Work",
        body: "Govern is the pillar that makes Run and Improve sustainable. Without governance, operational work becomes reactive and improvements introduce as many problems as they solve. The Govern pillar includes the design system as an active enforcement layer, where every change is validated against the token set before deployment. It includes DecisionOps logging, where every significant action is recorded with its rationale, its scope, and its outcome. It includes ContextOps coordination, which ensures that work across the five pipelines is aligned and free from conflicts. And it includes compliance monitoring, where regulatory requirements like accessibility standards are continuously checked rather than periodically audited. Governance is often the least understood pillar when clients first encounter Always On. It sounds like bureaucracy. In practice, it is the opposite. Good governance makes teams faster because they spend less time debating standards and more time delivering against them. It makes decisions better because precedent is documented and searchable. And it makes outcomes more predictable because the rules are explicit and enforced consistently. Clients experience governance as clarity. When they ask why something was done a particular way, there is always an answer. When they want to change direction, the implications are visible before the change is made. That is not bureaucracy. That is professionalism.",
      },
      {
        heading: "What This Costs and What It Replaces",
        body: "Always On is priced as a fixed monthly service. The exact amount depends on the size and complexity of the site, but the structure is the same for every client: a predictable monthly cost that covers Run, Improve, and Govern in full. There are no hourly rates, no change request fees, and no surprise invoices. This pricing model replaces several line items that clients are typically paying for separately: hosting and infrastructure management, a security monitoring service or the anxiety of not having one, ad hoc agency work for updates and improvements, periodic accessibility audits, annual or biennial redesign projects, and the internal time spent coordinating between these separate providers. When clients compare the Always On monthly cost against what they were spending across these fragmented services, the economics are consistently favourable. But cost is only part of the story. The real value is in what clients stop worrying about. They stop worrying about whether their site is secure. They stop wondering if their brand is being represented consistently. They stop dreading the conversation about the next redesign. Instead, they have a single relationship with a single team that handles everything, reports on everything, and improves everything. That is what Always On clients pay for. Not a website. Not a project. A managed operation that gets better every month, with full transparency and zero ambiguity about what is being delivered and why.",
      },
    ],
  },
];
